name: Generate GitHub Profile Trophies

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  trophy:
    runs-on: ubuntu-latest

    steps:
      - name: Generate trophy
        uses: Erik-Donath/github-profile-trophy@feature/generate-svg
        with:
          username: tsharanya2005
          output_path: trophy.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit trophy
        uses: EndBug/add-and-commit@v9
        with:
          message: "Update GitHub trophies"
          add: "trophy.svg"
